# discord bot token
token = ""

# eth wallet
eth_privkey = ""
eth_address = ""

# btc REST https://host:port
btc_url = "https://127.0.0.1:8080"
# btc admin.macaroon directory
btc_macaroon_dir = "path_to/admin.macaroon"

# ltc REST https://host:port
ltc_url = "https://127.0.0.1:8081"
# ltc admin.macaroon directory
ltc_macaroon_dir = "path_to/admin.macaroon"

# limit in hours
limit = 24

# websocket web3 providers
[providers]
ethereum = "wss://rinkeby.infura.io/ws/v3/......"
arbitrum = "wss://arbitrum-rinkeby.infura.io/ws/v3/......"

[coins]
BTC = { amount = 0.0001, network = "lightning", decimals = 8 }
LTC = { amount = 0.0001, network = "lightning", decimals = 8 }
ETH = { amount = 0.0001, network = "ethereum", decimals = 18 }
USDT = { amount = 0.0001, network = "ethereum", contract = "0xD92E713d051C37EbB2561803a3b5FBAbc4962431", decimals = 6 }
USDC = { amount = 0.0001, network = "ethereum", contract = "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b", decimals = 6 }
AETH = { amount = 0.0001, network = "arbitrum", decimals = 18 }
HDX = { amount = 0.0001, network = "arbitrum", contract = "0x2400BBf112Ed1C663CB14c9EafFeDc0C8Be03742", decimals = 9 }
